info:
  contact: {}
paths:
  /api/v1/copy:
    post:
      consumes:
      - application/json
      description: 将七牛云存储空间中的文件从一个位置复制到另一个位置
      parameters:
      - description: 源文件名
        in: query
        name: srcObject
        required: true
        type: string
      - description: 目标文件名
        in: query
        name: destObject
        required: true
        type: string
      - description: 是否强制覆盖目标文件（true/false，默认为 false）
        in: query
        name: force
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: 文件复制成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: srcKey、destKey 缺失或 force 参数无效
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 文件复制失败
          schema:
            additionalProperties: true
            type: object
      summary: 复制文件
      tags:
      - 文件管理
  /api/v1/delete:
    delete:
      consumes:
      - application/json
      description: 根据文件名删除七牛云中的文件
      parameters:
      - description: 文件名
        in: query
        name: objectName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 文件删除成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 缺少必要参数 objectName
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 文件删除失败
          schema:
            additionalProperties: true
            type: object
      summary: 删除文件
      tags:
      - 文件管理
  /api/v1/download:
    get:
      consumes:
      - application/json
      description: 根据文件名生成私有或公共的下载链接
      parameters:
      - description: 文件名
        in: query
        name: objectName
        required: true
        type: string
      - description: 访问类型 ('public' 或 'private')
        in: query
        name: accessType
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 生成下载链接成功，返回下载链接
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 缺少必要参数 objectName
          schema:
            additionalProperties: true
            type: object
      summary: 生成文件下载链接
      tags:
      - 文件管理
  /api/v1/list:
    get:
      consumes:
      - application/json
      description: 列出七牛云存储空间中的文件
      parameters:
      - description: 文件名前缀筛选条件
        in: query
        name: prefix
        type: string
      - description: 游标，继续从上次读取的标记处开始列出
        in: query
        name: marker
        type: string
      - description: 每次列举的最大文件数量 (1-1000)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 文件列表获取成功，返回文件信息及下一页游标
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 文件列表获取失败
          schema:
            additionalProperties: true
            type: object
      summary: 获取文件列表
      tags:
      - 文件管理
  /api/v1/move:
    post:
      consumes:
      - application/json
      description: 将七牛云存储空间中的文件从一个位置移动到另一个位置
      parameters:
      - description: 源文件名
        in: query
        name: srcObject
        required: true
        type: string
      - description: 目标文件名
        in: query
        name: destObject
        required: true
        type: string
      - description: 是否强制覆盖目标文件（true/false，默认为 false）
        in: query
        name: force
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: 文件移动成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: srcKey、destKey 缺失或 force 参数无效
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 文件移动失败
          schema:
            additionalProperties: true
            type: object
      summary: 移动文件
      tags:
      - 文件管理
  /api/v1/upload:
    get:
      consumes:
      - application/json
      description: 根据文件路径和目标对象名称，将文件上传至七牛云存储
      parameters:
      - description: 本地文件路径
        in: query
        name: filePath
        required: true
        type: string
      - description: 目标对象名称
        in: query
        name: objectName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 上传成功，返回文件信息
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 缺少必要参数 filePath 和 objectName
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 上传失败
          schema:
            additionalProperties: true
            type: object
      summary: 上传文件至七牛云
      tags:
      - 文件管理
swagger: "2.0"
